import java.awt.Image;
import javax.swing.ImageIcon;

class Images {
    final static Image nextIcon = new ImageIcon("Images/Next Icon.png").getImage();
    final static Image restartIcon = new ImageIcon("Images/Restart Icon.png").getImage();;
    final static Image menuIcon = new ImageIcon("Images/Menu Icon.png").getImage();
    final static Image [] levels = {new ImageIcon("Images/Level 1.png").getImage(), new ImageIcon("Images/Level 2.png").getImage(), new ImageIcon("Images/Level 3.png").getImage(), new ImageIcon("Images/Level 4.png").getImage(), new ImageIcon("Images/Level 5.png").getImage(), new ImageIcon("Images/Level 6.png").getImage(), new ImageIcon("Images/Level 7.png").getImage(), new ImageIcon("Images/Level 8.png").getImage(), new ImageIcon("Images/Level 9.png").getImage(), new ImageIcon("Images/Level 10.png").getImage(), new ImageIcon("Images/Level 11.png").getImage(), new ImageIcon("Images/Level 12.png").getImage(), new ImageIcon("Images/Level 13.png").getImage(), new ImageIcon("Images/Level 14.png").getImage(), new ImageIcon("Images/Level 15.png").getImage(), new ImageIcon("Images/Level 16.png").getImage(), new ImageIcon("Images/Level 17.png").getImage(), new ImageIcon("Images/Level 18.png").getImage(), new ImageIcon("Images/Level 19.png").getImage(), new ImageIcon("Images/Level 20.png").getImage(), new ImageIcon("Images/Level 21.png").getImage(), new ImageIcon("Images/Level 22.png").getImage(), new ImageIcon("Images/Level 23.png").getImage(), new ImageIcon("Images/Level 24.png").getImage()};
    final static Image player = new ImageIcon("Images/Player.png").getImage(); 
    final static Image box = new ImageIcon("Images/Box.png").getImage();
    final static Image connecterWhite = new ImageIcon("Images/Connecter.png").getImage();
    final static Image connecterBlue = new ImageIcon("Images/Connecter Blue.png").getImage();
    final static Image connecterRed = new ImageIcon("Images/Connecter Red.png").getImage();
    final static Image weightedButtonOn = new ImageIcon("Images/Weighted Button On.png").getImage();
    final static Image weightedButtonOff = new ImageIcon("Images/Weighted Button Off.png").getImage();
    final static Image buttonOn = new ImageIcon("Images/Button On.png").getImage();
    final static Image buttonOff = new ImageIcon("Images/Button Off.png").getImage();
    final static Image [] receiversOn = {new ImageIcon("Images/Receiver Blue N On.png").getImage(), new ImageIcon("Images/Receiver Blue W On.png").getImage(), new ImageIcon("Images/Receiver Blue S On.png").getImage(), new ImageIcon("Images/Receiver Blue E On.png").getImage(), new ImageIcon("Images/Receiver Red N On.png").getImage(), new ImageIcon("Images/Receiver Red W On.png").getImage(), new ImageIcon("Images/Receiver Red S On.png").getImage(), new ImageIcon("Images/Receiver Red E On.png").getImage()};
    final static Image [] receiversOff = {new ImageIcon("Images/Receiver Blue N Off.png").getImage(), new ImageIcon("Images/Receiver Blue W Off.png").getImage(), new ImageIcon("Images/Receiver Blue S Off.png").getImage(), new ImageIcon("Images/Receiver Blue E Off.png").getImage(), new ImageIcon("Images/Receiver Red N Off.png").getImage(), new ImageIcon("Images/Receiver Red W Off.png").getImage(), new ImageIcon("Images/Receiver Red S Off.png").getImage(), new ImageIcon("Images/Receiver Red E Off.png").getImage()};
    final static Image [][] doors = {{new ImageIcon("Images/Door w 0.png").getImage(), new ImageIcon("Images/Door w 1.png").getImage(), new ImageIcon("Images/Door w 2.png").getImage(), new ImageIcon("Images/Door w 3.png").getImage(), new ImageIcon("Images/Door w 4.png").getImage()}, {new ImageIcon("Images/Door a 0.png").getImage(), new ImageIcon("Images/Door a 1.png").getImage(), new ImageIcon("Images/Door a 2.png").getImage(), new ImageIcon("Images/Door a 3.png").getImage(), new ImageIcon("Images/Door a 4.png").getImage()}, {new ImageIcon("Images/Door s 0.png").getImage(), new ImageIcon("Images/Door s 1.png").getImage(), new ImageIcon("Images/Door s 2.png").getImage(), new ImageIcon("Images/Door s 3.png").getImage(), new ImageIcon("Images/Door s 4.png").getImage()}, {new ImageIcon("Images/Door d 0.png").getImage(), new ImageIcon("Images/Door d 1.png").getImage(), new ImageIcon("Images/Door d 2.png").getImage(), new ImageIcon("Images/Door d 3.png").getImage(), new ImageIcon("Images/Door d 4.png").getImage()}}; 
    final static Image star = new ImageIcon("Images/Star.png").getImage();
}